version: "3.9"

services:
  imgproxy:
    image: darthsim/imgproxy:v3.11
    restart: always
    environment:
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_TTL: "604800" # 1 week
      IMGPROXY_USE_S3: 'true'
      AWS_REGION: ap-southeast-1
      AWS_ACCESS_KEY_ID: AKIA3AG4GPMURQTULDWI   // key was deactived
      AWS_SECRET_ACCESS_KEY: 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 //  key was deactived
    ports:
      - "8080:8080"
    networks:
      - common

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cache:/data/cache
    restart: always
    networks:
      - common 
networks:
  common:
